### PR TITLE
Fix building on MinGW

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by hobu** [comment]
This PR currently does not compile cleanly on all three platforms that we test with continuous integration testing. Please fix your code to compile to ✅ before it can be considered for inclusion.

**Comment by MehdiChinoune** [comment]
@hobu I have pushed new changes, consider approving CI run.

**Comment by MehdiChinoune** [comment]
@hobu I have pushed new changes, consider approving CI run.

**Comment by MehdiChinoune** [comment]
The failure of macos job is unrelated to my PR.

**Pull request merged**
